apiVersion: v1
data:
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: cm9vdF9wYXNzd29yZA==
kind: Secret
metadata:
  name: drupal-mysql-secret
type: string