apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal-mysql
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        volumeMounts:
        - mountPath: "/var/lib/mysql/dbdata"
          name: drupal-mysql-pvc
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret
                key: MYSQL_USER
      volumes:
      - name: drupal-mysql-pvc
        persistentVolumeClaim:
          claimName: drupal-mysql-pvc