apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    name: drupal-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /drupal-data
    type: Directory
  accessModes:
  - ReadWriteOnce