apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  labels:
    name: wordpress-persistent-storage
spec:
  capacity:
    storage: 1Gi
  nfs:
    path: /html
    server: nfs01
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany